# Generated by Django 4.0.4 on 2022-06-30 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(through='softdesk.Contributor', to='softdesk.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(through='softdesk.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
