# Generated by Django 4.0.4 on 2022-07-26 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0004_contributor_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='characters must be Alphanumeric', regex='[a-zA-Z0-9\\s]')]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='characters must be Alphanumeric', regex='[a-zA-Z0-9\\s]')]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(default='undefined', max_length=255, validators=[django.core.validators.RegexValidator(message='characters must be Alphanumeric', regex='[a-zA-Z0-9\\s]')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='characters must be Alphanumeric', regex='[a-zA-Z0-9\\s]')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='undefined', max_length=255, validators=[django.core.validators.RegexValidator(message='characters must be Alphanumeric', regex='[a-zA-Z0-9\\s]')]),
        ),
    ]
