# Generated by Django 4.0.4 on 2022-07-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0008_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project_associated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributors', to='softdesk.project'),
        ),
    ]
